
server.port=8100

# ===============================
# CONFIGURATION POSTGRESQL
# ===============================
# L'URL de connexion
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/sepa26
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# CONFIGURATION HIBERNATE (JPA)
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# affiche les requêtes SQL dans la console pour débugger
spring.jpa.show-sql=true